### ISSUE TITLE
헤더 읽고 바디 출력하기.

### ISSUE THREAD

**Issue by kimsin3003** [433-Summer-Internship/Taewoo-Dongkyoo-Hyejin#1]

**Comment by lunker** [comment]
7월 28일 (목요일)까지!!!
각자 client/server 모두 구현. 

**Header** : 
- type : short (2byte)
- len : int(4byte) 

**Body** :
- 각자 알아서 

총 6byte

**Comment by kimsin3003** [comment]
모두 성공~
